sudo: false
dist: trusty
language: python
cache: pip
python:
    - "2.7.13"
    - "3.6"
install:
    - pip install --upgrade pip setuptools
    - pip install flake8
before_script:
    flake8 . --count --max-line-length=127 --statistics   # 127 == GitHub editor width
script:
    flake8 . --count --max-line-length=127 --select=E999  # Stop build on syntax errors
notifications:
    on_success: change
    on_failure: always
